package edu.utpl.swsoa.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.13
 * 2015-08-16T23:53:29.165-05:00
 * Generated source version: 2.7.13
 * 
 */
@WebService(targetNamespace = "http://ws.swsoa.utpl.edu/", name = "securityWS")
@XmlSeeAlso({ObjectFactory.class})
public interface SecurityWS {

    @WebMethod
    @Action(input = "http://ws.swsoa.utpl.edu/securityWS/buscarPersonaPorIdentificacionRequest", output = "http://ws.swsoa.utpl.edu/securityWS/buscarPersonaPorIdentificacionResponse")
    @RequestWrapper(localName = "buscarPersonaPorIdentificacion", targetNamespace = "http://ws.swsoa.utpl.edu/", className = "edu.utpl.swsoa.ws.BuscarPersonaPorIdentificacion")
    @ResponseWrapper(localName = "buscarPersonaPorIdentificacionResponse", targetNamespace = "http://ws.swsoa.utpl.edu/", className = "edu.utpl.swsoa.ws.BuscarPersonaPorIdentificacionResponse")
    @WebResult(name = "return", targetNamespace = "")
    public edu.utpl.swsoa.ws.Persona buscarPersonaPorIdentificacion(
        @WebParam(name = "identificacion", targetNamespace = "")
        java.lang.String identificacion
    );
    
}
