package edu.utpl.swsoa.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.13
 * 2015-08-16T23:53:29.197-05:00
 * Generated source version: 2.7.13
 * 
 */
@WebServiceClient(name = "servicioSoa", 
                  wsdlLocation = "http://localhost:8080/servicioSoa/securityWS?wsdl",
                  targetNamespace = "http://ws.swsoa.utpl.edu/") 
public class ServicioSoa extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://ws.swsoa.utpl.edu/", "servicioSoa");
    public final static QName SecurityWSPort = new QName("http://ws.swsoa.utpl.edu/", "securityWSPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/servicioSoa/securityWS?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ServicioSoa.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/servicioSoa/securityWS?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ServicioSoa(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ServicioSoa(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServicioSoa() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ServicioSoa(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ServicioSoa(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ServicioSoa(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns SecurityWS
     */
    @WebEndpoint(name = "securityWSPort")
    public SecurityWS getSecurityWSPort() {
        return super.getPort(SecurityWSPort, SecurityWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SecurityWS
     */
    @WebEndpoint(name = "securityWSPort")
    public SecurityWS getSecurityWSPort(WebServiceFeature... features) {
        return super.getPort(SecurityWSPort, SecurityWS.class, features);
    }

}
